### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Chris265** [haywardgb/ExpansionCustomLoadingScreen#1]
Hello, thank you for the mod :)

I am a bit inexperienced, but what resolution does the logo need? I would like to use my own logo instead of the expansion logo. 

Thank you and best regards.

**Comment by haywardgg** [comment]
> Hello, thank you for the mod :)
> 
> I am a bit inexperienced, but what resolution does the logo need? I would like to use my own logo instead of the expansion logo.
> 
> Thank you and best regards.

You're welcome.

If you look in the data folder you'll find the original logo , which is 444x208

**Comment by Chris265** [comment]
Thank you very much for the quick answer. Is it also possible to change the DayZ Expansion logo in the main menu with a custom one?

**Comment by haywardgg** [comment]
> Thank you very much for the quick answer. Is it also possible to change the DayZ Expansion logo in the main menu with a custom one?

Yes. You can simply convert your custom logo from png to edds using the DayZ Toolz. The same way you will need to convert your custom loading screen images from jpg/png to edds. Samples of each file are included and using DayZ Toolz you you can check the size's etc. Good luck.

**Comment by Chris265** [comment]
Okay, thank you very much. I have tried it. It also worked during loading. Unfortunately, the logo on the main screen remained unchanged.

**Comment by haywardgg** [comment]
> 

If you've added your own logo (replaced the original mylogo.edds) and you're seeing the default logo, then there's an issue with your scripts or the image you've uploaded.

**Comment by Chris265** [comment]
My logo works without any problems, unfortunately only in the loading screen and not in the main menu. Is that the way it's supposed to be? Maybe I have also misunderstood something ^^

**Comment by haywardgg** [comment]
That's correct, this is just a loading screen mod. The logo will only be for the loading screen. 

Hope that answers your question. 

If you're talking about the Watermark, check this video: https://www.youtube.com/watch?v=xbrETb_33zE

If you're talking about the Book Logo, check this video: https://www.youtube.com/watch?v=WDNAITImVPM

Good luck and I'm glad the loading screen mod works as intended.

**Comment by haywardgb** [comment]
This might also interest you: https://steamcommunity.com/sharedfiles/filedetails/?id=888177130

**Comment by Chris265** [comment]
Okay great, thanks for the info :) I'll have a look at that too. 

But I really meant the logo in the main menu. Here is a screenshot: [https://ibb.co/MCc76YD](url)

Greetings and thanks for everything.
